---
- hosts: 18.212.159.21
  sudo: yes

  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - mcrypt
      - nginx
      - php7.2-common
      - php7.2-cli
      - php7.2-curl
      - php7.2-fpm
      # - php7.2-intl
      - php7.2-json
      # - php7.2-mcrypt
      - php7.2-sqlite3
      - sqlite3
